// 발상 도구 내장 단어 풀·문장 틀 — 정본 (docs/IDEATION_SYSTEM.md §4).
// 단어는 DB v3 `ideation_words`의 시드 데이터(db/에 두는 이유: db/ → features/ import 금지). 사용자가 관리 화면에서 고친 뒤의 진실은 DB.
// 문장 틀(만약에)은 계속 이 파일이 정본. 언어별 앱 리소스: 번역이 아니라 각 언어에 자연스러운 단어를 따로 쓴다. 서버·AI 없음.
// 두 언어의 그룹 수·순서는 같아야 한다(assertPoolsAligned). 언어 안 중복 단어 금지(UNIQUE 시드). check:i18n 대상 아님(TS 데이터).

import type { AppLanguage } from '@/lib/i18n';

export interface WordGroup {
  /** 그룹 키 — 언어 공통(섞기 규칙 "다른 그룹에서" 판정에 쓴다) */
  key: string;
  words: string[];
}

export interface IdeationPool {
  groups: WordGroup[];
  /** 만약에… 문장 틀. `{X}` 자리 하나 */
  whatIf: string[];
}

const KO: IdeationPool = {
  groups: [
    {
      key: 'daily',
      words: [
        '아침 루틴',
        '출퇴근',
        '장보기',
        '집안일',
        '빨래',
        '알람',
        '수면',
        '일기',
        '약속',
        '택배',
        '청소',
        '옷장',
      ],
    },
    {
      key: 'health',
      words: [
        '홈트',
        '스트레칭',
        '걷기',
        '체중',
        '식단',
        '물 마시기',
        '명상',
        '수면 습관',
        '자세',
        '금연',
        '건강검진',
        '허리',
      ],
    },
    {
      key: 'parenting',
      words: [
        '육아',
        '아이 식사',
        '등하원',
        '숙제',
        '용돈',
        '놀이터',
        '그림책',
        '형제 다툼',
        '수면 교육',
        '아이 사진',
        '학부모 모임',
        '장난감 정리',
      ],
    },
    {
      key: 'sports',
      words: [
        '축구',
        '러닝',
        '자전거',
        '등산',
        '수영',
        '골프',
        '테니스',
        '헬스장',
        '배드민턴',
        '야구',
        '요가',
        '동호회',
      ],
    },
    {
      key: 'food',
      words: [
        '레시피',
        '도시락',
        '냉장고',
        '배달',
        '카페',
        '식당 웨이팅',
        '와인',
        '남은 음식',
        '식비',
        '혼밥',
        '베이킹',
        '캠핑 요리',
      ],
    },
    {
      key: 'travel',
      words: [
        '여행 계획',
        '짐 싸기',
        '숙소',
        '기차',
        '공항',
        '환전',
        '기념품',
        '사진 정리',
        '당일치기',
        '캠핑',
        '길찾기',
        '여행 일기',
      ],
    },
    {
      key: 'learning',
      words: [
        '영어 단어',
        '독서',
        '자격증',
        '온라인 강의',
        '필기',
        '암기',
        '시험 일정',
        '스터디',
        '악기 연습',
        '외국어 회화',
        '코딩 공부',
        '수학',
      ],
    },
    {
      key: 'money',
      words: [
        '가계부',
        '비상금',
        '구독료',
        '중고 거래',
        '할인',
        '적금',
        '영수증',
        '공동 지출',
        '더치페이',
        '월급',
        '세금',
        '기부',
      ],
    },
    {
      key: 'work',
      words: [
        '회의',
        '할 일',
        '이메일',
        '프리랜서',
        '재택근무',
        '점심 메뉴',
        '명함',
        '출장',
        '보고서',
        '팀 일정',
        '면접',
        '이직',
      ],
    },
    {
      key: 'hobby',
      words: [
        '사진',
        '식물 키우기',
        '뜨개질',
        '기타',
        '보드게임',
        '영화 기록',
        '드로잉',
        '낚시',
        '음악 플레이리스트',
        '수집',
        '퍼즐',
        '글쓰기',
      ],
    },
    {
      key: 'tech',
      words: [
        'QR 코드',
        '음성 메모',
        '위젯',
        '알림',
        '스마트워치',
        '위치 공유',
        '카메라',
        'NFC',
        '단축어',
        '자동화',
        '블루투스',
        '오프라인',
      ],
    },
    {
      key: 'environment',
      words: [
        '분리수거',
        '텀블러',
        '전기 요금',
        '중고',
        '채식',
        '걷기 출근',
        '나눔',
        '재활용',
        '탄소',
        '식물',
        '빗물',
        '동네 청소',
      ],
    },
    {
      key: 'pets',
      words: [
        '강아지 산책',
        '고양이 사료',
        '동물병원',
        '펫시터',
        '유기동물',
        '반려동물 사진',
        '배변 훈련',
        '펫 용품',
        '산책 친구',
        '털 관리',
        '이름 짓기',
        '입양',
      ],
    },
    {
      key: 'games',
      words: [
        '퀴즈',
        '랭킹',
        '미션',
        '뽑기',
        '레벨',
        '협동',
        '타이머 대결',
        '스탬프',
        '보물찾기',
        '빙고',
        '카드 게임',
        '스피드런',
      ],
    },
    {
      key: 'local',
      words: [
        '동네 가게',
        '아파트 커뮤니티',
        '주차',
        '도서관',
        '공원',
        '벼룩시장',
        '이웃',
        '맛집 지도',
        '버스 시간',
        '분실물',
        '동네 소식',
        '공동구매',
      ],
    },
  ],
  whatIf: [
    '{X}를 아이용으로 만들면?',
    '{X}를 60대 부모님이 쓴다면?',
    '{X}에서 화면을 없애고 소리만 남기면?',
    '{X}를 하루 5분만 할 수 있게 줄이면?',
    '{X}를 친구와 둘이서만 하게 만들면?',
    '{X}를 완전히 익명으로 하면?',
    '{X}를 게임처럼 점수를 매기면?',
    '{X}를 구독으로 바꾸면?',
    '{X}를 반대로 하면 어떻게 될까?',
    '{X}를 종이 한 장으로 해결하면?',
    '{X}를 인터넷 없이 하려면?',
    '{X}를 1인 가구에 맞추면?',
    '{X}를 반려동물과 함께하면?',
    '{X}를 동네 사람들과 나누면?',
    '{X}에 타이머를 붙이면?',
    '{X}를 사진 한 장으로 기록하면?',
    '{X}를 음성으로만 조작하면?',
    '{X}를 매일 같은 시간에 하게 만들면?',
    '{X}를 선물처럼 포장하면?',
    '{X}를 초보자만을 위해 다시 만들면?',
    '{X}를 전문가만을 위해 다시 만들면?',
    '{X}에서 가장 귀찮은 단계를 없애면?',
    '{X}를 10배 비싸게 팔 수 있다면 뭐가 달라야 할까?',
    '{X}를 무료로 만들고 다른 데서 돈을 번다면?',
    '{X}를 가족 전체가 함께 쓰면?',
    '{X}를 여행 중에만 쓴다면?',
    '{X}를 스마트워치에서만 한다면?',
    '{X}를 편지처럼 느리게 만들면?',
    '{X}를 경쟁 대신 협동으로 바꾸면?',
    '{X}를 한 번 쓰고 버리는 것으로 만들면?',
    '{X}를 평생 한 번만 하는 것으로 만들면?',
    '{X}를 지도 위에 올리면?',
    '{X}를 달력 위에 올리면?',
    '{X}를 사람 대신 사물이 한다면?',
    '{X}를 대화 형식으로 바꾸면?',
    '{X}를 소리 없이 진동만으로 알려주면?',
    '{X}를 시각장애인이 쓴다면 무엇이 필요할까?',
    '{X}를 아주 느린 인터넷에서 쓴다면?',
    '{X}를 명절에만 쓴다면?',
    '{X}를 은퇴 후에 한다면?',
  ],
};

const EN: IdeationPool = {
  groups: [
    {
      key: 'daily',
      words: [
        'morning routine',
        'commute',
        'groceries',
        'chores',
        'laundry',
        'alarms',
        'sleep',
        'journaling',
        'appointments',
        'deliveries',
        'cleaning',
        'wardrobe',
      ],
    },
    {
      key: 'health',
      words: [
        'home workout',
        'stretching',
        'walking',
        'weight',
        'diet',
        'drinking water',
        'meditation',
        'sleep habits',
        'posture',
        'quitting smoking',
        'checkups',
        'back pain',
      ],
    },
    {
      key: 'parenting',
      words: [
        'parenting',
        'kids meals',
        'school run',
        'homework',
        'allowance',
        'playground',
        'picture books',
        'sibling fights',
        'sleep training',
        'kid photos',
        'parent groups',
        'toy cleanup',
      ],
    },
    {
      key: 'sports',
      words: [
        'soccer',
        'running',
        'cycling',
        'hiking',
        'swimming',
        'golf',
        'tennis',
        'the gym',
        'badminton',
        'baseball',
        'yoga',
        'sports clubs',
      ],
    },
    {
      key: 'food',
      words: [
        'recipes',
        'lunch boxes',
        'the fridge',
        'food delivery',
        'cafes',
        'restaurant waits',
        'wine',
        'leftovers',
        'food budget',
        'eating alone',
        'baking',
        'camp cooking',
      ],
    },
    {
      key: 'travel',
      words: [
        'trip planning',
        'packing',
        'lodging',
        'trains',
        'airports',
        'currency exchange',
        'souvenirs',
        'photo sorting',
        'day trips',
        'camping',
        'wayfinding',
        'travel journals',
      ],
    },
    {
      key: 'learning',
      words: [
        'vocabulary',
        'reading',
        'certifications',
        'online courses',
        'note-taking',
        'memorization',
        'exam schedules',
        'study groups',
        'instrument practice',
        'conversation practice',
        'learning to code',
        'math',
      ],
    },
    {
      key: 'money',
      words: [
        'budgeting',
        'emergency fund',
        'subscriptions',
        'second-hand deals',
        'discounts',
        'savings',
        'receipts',
        'shared expenses',
        'splitting bills',
        'payday',
        'taxes',
        'donations',
      ],
    },
    {
      key: 'work',
      words: [
        'meetings',
        'to-dos',
        'email',
        'freelancing',
        'remote work',
        'lunch choices',
        'business cards',
        'business trips',
        'reports',
        'team calendars',
        'interviews',
        'job changes',
      ],
    },
    {
      key: 'hobby',
      words: [
        'photography',
        'houseplants',
        'knitting',
        'guitar',
        'board games',
        'movie logs',
        'drawing',
        'fishing',
        'playlists',
        'collecting',
        'puzzles',
        'writing',
      ],
    },
    {
      key: 'tech',
      words: [
        'QR codes',
        'voice memos',
        'widgets',
        'notifications',
        'smartwatches',
        'location sharing',
        'the camera',
        'NFC',
        'shortcuts',
        'automation',
        'Bluetooth',
        'offline mode',
      ],
    },
    {
      key: 'environment',
      words: [
        'recycling',
        'reusable cups',
        'electricity bills',
        'second-hand',
        'plant-based eating',
        'walking to work',
        'sharing',
        'upcycling',
        'carbon footprint',
        'plants',
        'rainwater',
        'neighborhood cleanups',
      ],
    },
    {
      key: 'pets',
      words: [
        'dog walks',
        'cat food',
        'the vet',
        'pet sitters',
        'shelter animals',
        'pet photos',
        'house training',
        'pet supplies',
        'walking buddies',
        'grooming',
        'naming a pet',
        'adoption',
      ],
    },
    {
      key: 'games',
      words: [
        'quizzes',
        'leaderboards',
        'missions',
        'gacha',
        'levels',
        'co-op',
        'timer duels',
        'stamp cards',
        'treasure hunts',
        'bingo',
        'card games',
        'speedruns',
      ],
    },
    {
      key: 'local',
      words: [
        'local shops',
        'apartment communities',
        'parking',
        'libraries',
        'parks',
        'flea markets',
        'neighbors',
        'restaurant maps',
        'bus times',
        'lost and found',
        'local news',
        'group buying',
      ],
    },
  ],
  whatIf: [
    'What if {X} were made for kids?',
    'What if your 60-year-old parents used {X}?',
    'What if {X} had no screen — only sound?',
    'What if {X} took only 5 minutes a day?',
    'What if {X} could only be done with one friend?',
    'What if {X} were completely anonymous?',
    'What if {X} were scored like a game?',
    'What if {X} became a subscription?',
    'What if you did {X} backwards?',
    'What if {X} fit on a single sheet of paper?',
    'What if {X} worked without the internet?',
    'What if {X} were built for people living alone?',
    'What if {X} were done together with a pet?',
    'What if {X} were shared with your neighbors?',
    'What if {X} had a timer?',
    'What if {X} were recorded as one photo?',
    'What if {X} were controlled by voice only?',
    'What if {X} happened at the same time every day?',
    'What if {X} were wrapped like a gift?',
    'What if {X} were rebuilt for complete beginners?',
    'What if {X} were rebuilt for experts only?',
    'What if the most annoying step of {X} disappeared?',
    'What would have to change to sell {X} at 10× the price?',
    'What if {X} were free and the money came from somewhere else?',
    'What if the whole family used {X} together?',
    'What if {X} were used only while traveling?',
    'What if {X} lived only on a smartwatch?',
    'What if {X} were slow, like a letter?',
    'What if {X} were cooperative instead of competitive?',
    'What if {X} were disposable — used once?',
    'What if {X} were done once in a lifetime?',
    'What if {X} were laid out on a map?',
    'What if {X} were laid out on a calendar?',
    'What if an object did {X} instead of a person?',
    'What if {X} were a conversation?',
    'What if {X} alerted you with vibration only?',
    'What would {X} need if a blind person used it?',
    'What if {X} ran on a very slow connection?',
    'What if {X} were used only on holidays?',
    'What if {X} were done after retirement?',
  ],
};

export const POOLS: Record<AppLanguage, IdeationPool> = { en: EN, ko: KO };

/** 두 언어의 그룹 키·순서가 같은지 — 개발 중 어긋남을 즉시 드러낸다 */
export function assertPoolsAligned(): void {
  const a = EN.groups.map((g) => g.key).join(',');
  const b = KO.groups.map((g) => g.key).join(',');
  if (a !== b) throw new Error(`ideation pools misaligned: en=[${a}] ko=[${b}]`);
}

export function getPool(lang: string): IdeationPool {
  return lang.startsWith('ko') ? KO : EN;
}

/** 그룹 키 순서(언어 공통) — 관리 화면 섹션·정렬 기준. 사용자 단어 그룹 'mine'은 맨 뒤 */
export const POOL_GROUP_KEYS: readonly string[] = EN.groups.map((g) => g.key);

/** 언어 안 중복(대소문자 무시)이 없는지 — UNIQUE 시드가 깨지지 않게 개발 중 즉시 드러낸다 */
export function assertPoolsUnique(): void {
  for (const [lang, pool] of Object.entries(POOLS)) {
    const seen = new Set<string>();
    for (const g of pool.groups)
      for (const w of g.words) {
        const k = w.toLowerCase();
        if (seen.has(k)) throw new Error(`ideation pool duplicate (${lang}): ${w}`);
        seen.add(k);
      }
  }
}

// 개발 빌드에서 모듈 로드 시 즉시 검사 — 릴리스에서는 비용 0
if (__DEV__) {
  assertPoolsAligned();
  assertPoolsUnique();
}
