// 테마 정본 — 팔레트 객체 하나 추가 = 테마 하나 추가 (docs/THEME_SYSTEM.md).
// hex는 docs/design/theme-mockups-12.png 시안에서 추출한 근사값. 실기기 대조로 조정한다.
// 컴포넌트는 색상 리터럴 금지 — 이 토큰만 참조한다.

export const THEME_IDS = [
  'lightMinimal',
  'darkMinimal',
  'softPurple',
  'mintClean',
  'oceanBlue',
  'warmBeige',
  'monotone',
  'lightGlass',
  'natureLight',
  'simpleNavy',
  'gradientMinimal',
  'colorPoint',
] as const;

export type ThemeId = (typeof THEME_IDS)[number];

/** 설정값 — system이면 OS 라이트/다크에 따라 Light/Dark Minimal (THEME_SYSTEM 결정 이력) */
export type ThemeSetting = 'system' | ThemeId;
export const DEFAULT_THEME_SETTING: ThemeSetting = 'system';
export const SYSTEM_LIGHT: ThemeId = 'lightMinimal';
export const SYSTEM_DARK: ThemeId = 'darkMinimal';

export interface ThemePalette {
  id: ThemeId;
  isDark: boolean; // 상태바·헤더 콘텐츠 스타일 파생
  background: string;
  surface: string;
  card: string;
  searchBar: string;
  primary: string;
  text: string;
  textMuted: string;
  icon: string;
  button: string;
  buttonText: string;
  border: string; // 카드 테두리(1px) — 희미하지 않게 (2026-08-17 사용자 지적)
  badge: string;
  badgeText: string;
  danger: string;
  progressTrack: string;
  progressFill: string;
  /** 컬러 포인트 테마 전용 — 카드마다 순환하는 포인트 컬러(왼쪽 바). 없으면 바 없음 */
  cardAccents?: string[];
}

const RED = '#DC2626';
const RED_DARK = '#F87171';

export const THEMES: Record<ThemeId, ThemePalette> = {
  lightMinimal: {
    id: 'lightMinimal',
    isDark: false,
    background: '#FFFFFF',
    surface: '#F5F6F8',
    card: '#FFFFFF',
    searchBar: '#F1F3F5',
    primary: '#2563EB',
    text: '#111827',
    textMuted: '#6B7280',
    icon: '#374151',
    button: '#2563EB',
    buttonText: '#FFFFFF',
    border: '#D9DEE5',
    badge: '#F3F4F6',
    badgeText: '#374151',
    danger: RED,
    progressTrack: '#E5E7EB',
    progressFill: '#2563EB',
  },
  darkMinimal: {
    id: 'darkMinimal',
    isDark: true,
    background: '#0F0F12',
    surface: '#18181C',
    card: '#1E1E24',
    searchBar: '#1E1E24',
    primary: '#6366F1',
    text: '#F3F4F6',
    textMuted: '#9CA3AF',
    icon: '#D1D5DB',
    button: '#6366F1',
    buttonText: '#FFFFFF',
    border: '#33333C',
    badge: '#2A2A32',
    badgeText: '#D1D5DB',
    danger: RED_DARK,
    progressTrack: '#2C2C34',
    progressFill: '#6366F1',
  },
  softPurple: {
    id: 'softPurple',
    isDark: false,
    background: '#F7F5FD',
    surface: '#EFEBFB',
    card: '#FFFFFF',
    searchBar: '#F1EEFA',
    primary: '#7C3AED',
    text: '#1F1B2E',
    textMuted: '#6B6480',
    icon: '#5B4B8A',
    button: '#7C3AED',
    buttonText: '#FFFFFF',
    border: '#DCD4F2',
    badge: '#EDE7FA',
    badgeText: '#5B4B8A',
    danger: RED,
    progressTrack: '#E7E1F7',
    progressFill: '#7C3AED',
  },
  mintClean: {
    id: 'mintClean',
    isDark: false,
    background: '#FFFFFF',
    surface: '#F0FAF6',
    card: '#FFFFFF',
    searchBar: '#F1F5F3',
    primary: '#10B981',
    text: '#10251C',
    textMuted: '#6B7C74',
    icon: '#2F6B54',
    button: '#10B981',
    buttonText: '#FFFFFF',
    border: '#CFE6DB',
    badge: '#E6F6EF',
    badgeText: '#2F6B54',
    danger: RED,
    progressTrack: '#E3EFE9',
    progressFill: '#10B981',
  },
  oceanBlue: {
    id: 'oceanBlue',
    isDark: false,
    background: '#EEF6FF',
    surface: '#E3F0FF',
    card: '#FFFFFF',
    searchBar: '#F3F8FF',
    primary: '#2E90FA',
    text: '#10233A',
    textMuted: '#5C7590',
    icon: '#2C5A8A',
    button: '#2E90FA',
    buttonText: '#FFFFFF',
    border: '#C9DDF4',
    badge: '#E1EEFC',
    badgeText: '#2C5A8A',
    danger: RED,
    progressTrack: '#DCE9F7',
    progressFill: '#2E90FA',
  },
  warmBeige: {
    id: 'warmBeige',
    isDark: false,
    background: '#FBF7F1',
    surface: '#F4ECE0',
    card: '#FFFDF9',
    searchBar: '#F5EFE6',
    primary: '#C2410C',
    text: '#2B1F14',
    textMuted: '#7C6A58',
    icon: '#8A5A2B',
    button: '#C2410C',
    buttonText: '#FFFFFF',
    border: '#E3D5C1',
    badge: '#F1E7D8',
    badgeText: '#8A5A2B',
    danger: '#B91C1C',
    progressTrack: '#EADFCF',
    progressFill: '#C2410C',
  },
  monotone: {
    id: 'monotone',
    isDark: false,
    background: '#FFFFFF',
    surface: '#F4F4F5',
    card: '#FFFFFF',
    searchBar: '#F1F1F2',
    primary: '#111111',
    text: '#111111',
    textMuted: '#71717A',
    icon: '#27272A',
    button: '#111111',
    buttonText: '#FFFFFF',
    border: '#D4D4D8',
    badge: '#EFEFF1',
    badgeText: '#27272A',
    danger: RED,
    progressTrack: '#E4E4E7',
    progressFill: '#111111',
  },
  lightGlass: {
    id: 'lightGlass',
    isDark: false,
    background: '#E9EFF8',
    surface: '#DEE7F4',
    card: '#F6F9FD',
    searchBar: '#F3F6FB',
    primary: '#3B82F6',
    text: '#1E293B',
    textMuted: '#64748B',
    icon: '#334155',
    button: '#3B82F6',
    buttonText: '#FFFFFF',
    border: '#C3D2E6',
    badge: '#E2EAF6',
    badgeText: '#334155',
    danger: RED,
    progressTrack: '#D6E0EF',
    progressFill: '#3B82F6',
  },
  natureLight: {
    id: 'natureLight',
    isDark: false,
    background: '#F5FAF3',
    surface: '#EAF4E6',
    card: '#FFFFFF',
    searchBar: '#EFF6EC',
    primary: '#4D9A3A',
    text: '#1B2E1F',
    textMuted: '#5C7060',
    icon: '#3C6B44',
    button: '#4D9A3A',
    buttonText: '#FFFFFF',
    border: '#CFE3C8',
    badge: '#E6F1E1',
    badgeText: '#3C6B44',
    danger: RED,
    progressTrack: '#DFEBD9',
    progressFill: '#4D9A3A',
  },
  simpleNavy: {
    id: 'simpleNavy',
    isDark: true,
    background: '#0F172A',
    surface: '#16213A',
    card: '#1C2740',
    searchBar: '#1C2740',
    primary: '#3B82F6',
    text: '#E5EAF3',
    textMuted: '#94A3B8',
    icon: '#CBD5E1',
    button: '#3B82F6',
    buttonText: '#FFFFFF',
    border: '#31405E',
    badge: '#24314B',
    badgeText: '#CBD5E1',
    danger: RED_DARK,
    progressTrack: '#2A3752',
    progressFill: '#3B82F6',
  },
  gradientMinimal: {
    id: 'gradientMinimal',
    isDark: false,
    background: '#FDF4F8',
    surface: '#F9E4EE',
    card: '#FFFFFF',
    searchBar: '#FBEFF5',
    primary: '#EC4899',
    text: '#1F1B24',
    textMuted: '#7A6B75',
    icon: '#9D3F71',
    button: '#EC4899',
    buttonText: '#FFFFFF',
    border: '#EDCCDC',
    badge: '#FBE7F0',
    badgeText: '#9D3F71',
    danger: RED,
    progressTrack: '#F3DDE7',
    progressFill: '#EC4899',
  },
  colorPoint: {
    id: 'colorPoint',
    isDark: false,
    background: '#FFFFFF',
    surface: '#F5F6F8',
    card: '#FFFFFF',
    searchBar: '#F1F3F5',
    primary: '#2563EB',
    text: '#111827',
    textMuted: '#6B7280',
    icon: '#374151',
    button: '#2563EB',
    buttonText: '#FFFFFF',
    border: '#D9DEE5',
    badge: '#F3F4F6',
    badgeText: '#374151',
    danger: RED,
    progressTrack: '#E5E7EB',
    progressFill: '#2563EB',
    cardAccents: ['#2563EB', '#F59E0B', '#10B981', '#DB2777', '#8B5CF6', '#EF4444'],
  },
};
